[package]
name = "reqwest-ext"
description = "Extensions for reqwest"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
license = "MPL-2.0"
edition = "2021"

[dependencies]
headers = "0.3"
reqwest = { version = "0.11", default-features = false }
sealed = "0.5"
