[package]
name = "reqwest-ext"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
edition = "2018"

[dependencies]
headers = "0.3"
http = "0.2"
reqwest = { git = "https://github.com/seanmonstar/reqwest" }
